import assert from "node:assert/strict";
import { performance } from "node:perf_hooks";
import {
  cloneProject,
  detectConflicts,
  renderDocumentation,
  sampleProject
} from "../logic.js";

function buildLargeProject(cardCount = 360) {
  const project = cloneProject(sampleProject);
  project.topics = [
    {
      id: "perf-topic",
      title: "Performance Topic",
      summary: "Synthetic release performance coverage.",
      cardIds: []
    }
  ];
  project.cards = [];
  project.links = [];

  for (let index = 0; index < cardCount; index += 1) {
    const id = `perf-card-${index}`;
    project.topics[0].cardIds.push(id);
    project.cards.push({
      id,
      title: `Performance Card ${index}`,
      summary: "Synthetic card used to bound logic workspace rendering cost.",
      details: "Generated by the preview performance test.",
      status: index % 9 === 0 ? "running" : "ready",
      linkedFiles: [`src/module-${index % 24}.ts`, `docs/topic-${index % 12}.md`],
      dependencies: index > 0 && index % 13 === 0 ? [`perf-card-${index - 1}`] : [],
      relatedCards: [],
      implementationBranch: null,
      worktreePath: null,
      conflicts: []
    });
  }

  return project;
}

function measure(label, budgetMs, fn) {
  const started = performance.now();
  const result = fn();
  const elapsed = performance.now() - started;
  assert.ok(elapsed < budgetMs, `${label} took ${elapsed.toFixed(1)}ms, budget ${budgetMs}ms`);
  console.log(`ok - ${label} (${elapsed.toFixed(1)}ms)`);
  return result;
}

const project = buildLargeProject();
const conflicts = measure("detects conflicts in large project", 250, () => detectConflicts(project));
assert.ok(conflicts.length > 0, "large project should produce merge-agent conflict coverage");

const handoff = measure("renders handoff documentation in large project", 300, () =>
  renderDocumentation(project, "handoff")
);
assert.equal(handoff.format, "markdown");
assert.ok(handoff.content.includes("Performance Card 0"));

const website = measure("renders website documentation in large project", 300, () =>
  renderDocumentation(project, "website")
);
assert.equal(website.format, "website");
assert.equal(website.topics[0].cards.length, project.cards.length);

console.log("Preview performance tests passed.");
